### ISSUE TITLE
Strange behavior on two monitors

### ISSUE THREAD

**Issue by arleenlasleur** [Aqaao/DockerUnderCursor#1]
Hello, I've attempted to assign Tool options (sharedtooldocker), it shows floating by hotkey but sticks to UI as regular turned on docker (and won't hide, dragging it off UI affects nothing, close button does not hide docker, e. g. it always visble). Also, I encountered this error:

```
AttributeError
Python 3.8.1: C:\krita\bin\krita.exe
Sat Dec  3 15:32:37 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\Admin\AppData\Roaming\krita\pykrita\dockerundercursor\dockermonitor.py in eventFilter(self=<dockerundercursor.dockermonitor.DockerMonitor object>, obj=<PyQt5.QtWidgets.QDockWidget object>, event=<PyQt5.QtCore.QEvent object>)
   14             if event.type() == QEvent.Leave:
   15                 wobj = QApplication.widgetAt(QCursor.pos())
   16                 if not self.dockermanager.checkParent(wobj):
   17                     self.dockermanager.dockerReturn()
   18                     return True
self = <dockerundercursor.dockermonitor.DockerMonitor object>
self.dockermanager = <dockerundercursor.dockertogglemanager.DockerToggleManager object>
self.dockermanager.checkParent = <bound method DockerToggleManager.checkParent of....dockertogglemanager.DockerToggleManager object>>
wobj = None

 C:\Users\Admin\AppData\Roaming\krita\pykrita\dockerundercursor\dockertogglemanager.py in checkParent(self=<dockerundercursor.dockertogglemanager.DockerToggleManager object>, obj=None)
  103 
  104     def checkParent(self,obj):
  105         pobj = obj.parent()
  106         if pobj == self.widget:
  107             return True
pobj undefined
obj = None
obj.parent undefined
AttributeError: 'NoneType' object has no attribute 'parent'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'NoneType' object has no attribute 'parent'",)
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\krita\pykrita\dockerundercursor\dockermonitor.py", line 16, in eventFilter
    if not self.dockermanager.checkParent(wobj):
  File "C:\Users\Admin\AppData\Roaming\krita\pykrita\dockerundercursor\dockertogglemanager.py", line 105, in checkParent
    pobj = obj.parent()
AttributeError: 'NoneType' object has no attribute 'parent'
```

How can I:
- keep docker on secondary monitor (I need to see it's state)
- but summon it on main monitor by hotkey (I can only move mouse cursor by stulys on main monitor, for secondary one it requires to take the mouse in hand)
- once cursor left docker area, it returns to secondary monitor (I believe it's default "hide" behavior). The docker WON'T come on the second monitor's area which I defined in workspace, but DOES sticks (snap) to main Krita interface, as in default workspace.

Something strange seems to be happen with docker window floating state, maybe somewhere it's hardcoded to zero/default.

Upd: AttributeError happens when the mouse cursor coordinates become lefter than coordinates of docker (Xdock < Xmouse). Or maybe when mouse leave main Krita window, this is not so clear for now.

Upd2: It maybe offtop but I trying to say I attempting to get the coordinates change plus show/hide of docker rather than it's show/hide only. Is this technically possible?

**Comment by Aqaao** [comment]
> it shows floating by hotkey but sticks to UI as regular turned on docker (and won't hide, dragging it off UI affects nothing, close button does not hide docker, e. g. it always visble)

I don't quite understand, can you take a screenshot?

> AttributeError: 'NoneType' object has no attribute 'parent'

I fixed it, already pulled.

> * keep docker on secondary monitor (I need to see it's state)
> 
> * but summon it on main monitor by hotkey (I can only move mouse cursor by stulys on main monitor, for secondary one it requires to take the mouse in hand)
> 
> * once cursor left docker area, it returns to secondary monitor (I believe it's default "hide" behavior). The docker WON'T come on the second monitor's area which I defined in workspace, but DOES sticks (snap) to main Krita interface, as in default workspace.

Solution 1:
You can click top menu that **Window-New Window**, then click **Window-New View** in new window and choose your document. Close all docker in first window, retain only the canvas. Use first window to draw and show docker by hotkey, use second window to check status. You can save the Window Layout for next time.

Solution 2:
New features using the plugin, press ctrl+~ to fix floating docker. But it's not finished yet, restarting krita or switching to canvas-only mode will clear the fix state.

As you can see, this new feature seems to be what you want, but saving the pin status automatically is a difficult task and I will find a way to improve it. Solution 1 may be better for you at this time.

**Comment by arleenlasleur** [comment]
Thanks for reply, I will try (1). Is it necessary post here or in forum (to show others dual-monitor usage)? I believe this issue may be closed.

**Comment by Aqaao** [comment]
> Thanks for reply, I will try (1). Is it necessary post here or in forum (to show others dual-monitor usage)? I believe this issue may be closed.

you can post it in forum.
