### ISSUE TITLE
AttributeError: 'DockerVisibilityToggler' object has no attribute 'selfIsParent'

### ISSUE THREAD

**Issue by rebuilder** [Aqaao/DockerUnderCursor#3]
When I try to use the plugin with the shortcut key I defined, I get the error below. 

AttributeError
Python 3.10.7: /usr/bin/python3
Tue Jun 25 08:34:13 2024

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/rebuilder/.local/share/krita/pykrita/dockerundercursor/docker_under_cursor.py in _pin_docker(self=<dockerundercursor.docker_under_cursor.DockerUnderCursor object>)
   57     def _pin_docker(self):
   58         for d in DockerVisibilityToggler.INSTANCES:
   59             if d.selfIsParent()[0]:
   60                 if d.pinned == False:
   61                     d.pin()
d = <dockerundercursor.docker_visibility_toggler.DockerVisibilityToggler object>
d.selfIsParent undefined
AttributeError: 'DockerVisibilityToggler' object has no attribute 'selfIsParent'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'DockerVisibilityToggler' object has no attribute 'selfIsParent'",)
    name = 'selfIsParent'
    obj = <dockerundercursor.docker_visibility_toggler.DockerVisibilityToggler object>
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/rebuilder/.local/share/krita/pykrita/dockerundercursor/docker_under_cursor.py", line 59, in _pin_docker
    if d.selfIsParent()[0]:
AttributeError: 'DockerVisibilityToggler' object has no attribute 'selfIsParent'

**Comment by rebuilder** [comment]
Sorry! I misused the plugin. I had set a shortcut to "pin docker", not to show the docker I wanted.

**Comment by Aqaao** [comment]
Current Pin function indeed had bug, I'm trying to fix it. You can use the Release version, v1.0.0 does not this error.

**Comment by Aqaao** [comment]
Fixed [Commit 2c5b12](https://github.com/Aqaao/DockerUnderCursor/commit/2c5b1265ad7377c7fe0079e870d11c1ab2ca87e7)
